language: node_js
node_js:
- 9.5.0
cache:
  directories:
    - "node_modules"
install:
  - npm install babel-cli mocha -g
  - npm install babel-core babel-preset-es2015 body-parser chai express
  - npm run build
